### ISSUE TITLE
一起来学 cs224n

### ISSUE THREAD

**Issue by sunoonlee** [sunoonlee/cs224n#1]
* 各自建立 cs224n github 学习仓库，可以互相 watch 仓库
* 以输出为导向的学习：学习笔记，动手练习，作业。用 commit 信息在同侪的 github 时间线上创造压力。
  * notes: 每学完一个 lecture，输出笔记，长短随意
  * exercises: 在作业之外，为自己创造小的练习机会
  * assignments: cs224n 有四次作业
* 大致节奏为每周两个 lecture，跟课程安排（http://web.stanford.edu/class/cs224n/syllabus.html ）一致。比这快些或慢些都 ok。
* 有需要讨论的问题，在自己仓库里发 issue

学友仓库：
* xpgeng：https://github.com/xpgeng/cs224n
* ruibofeng: https://github.com/ruibofeng/cs224n
* sunoonlee：https://github.com/sunoonlee/cs224n
* 你的仓库？快来~

**Comment by linbojin** [comment]
Hi, 我也正在学习，https://github.com/linbojin/cs224n-notes ，多多指教，如何加群呢？

**Comment by sunoonlee** [comment]
@linbojin 已邀请加入 deepNLP 讨论组 https://groups.google.com/forum/#!forum/deepnlp 
欢迎一起交流讨论

**Comment by JyiHUO** [comment]
@linbojin 你好啊，我刚刚完成cs224n的assignment 1的word2vec。请问可以加入到你们的讨论组么？
